### ISSUE TITLE
Custom Domain für die Dokumentation

### ISSUE THREAD

**Issue by Kasperczyk** [opitzconsulting/orcas#37]
Aktuell ist die Dokumentation über die Standard URL für Projekt-gh-pages erreichbar (<user/organization>.github.io/<project name>/, in unserem Fall folglich http://opitzconsulting.github.io/orcas/).

gh-pages ermöglichen aber auch eine Custom Domain.

Anleitungen:

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
https://help.github.com/articles/adding-a-cname-file-to-your-repository/
https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/

Fragestellungen:

1. Ist eine Custom Domain überhaupt gewünscht oder sind wir zufrieden mit der Default URL? Wenn zufrieden -> **Nicht weiterlesen und Issue schließen!**
2. Wenn pro Custom Domain: Wie soll sie lauten? Namensvorschläge?
3. Wer kann das mit dem DNS Provider klären? (interne IT vermutlich!?)

**Comment by rattermeyer** [comment]
generell finde ich das auch eine gute Idee. bin leider erst durch den close aufmerksam geworden.
@llsand : Gibt es dazu eine Entscheidung?

**Comment by llsand** [comment]
Nein, eine Entscheidung gab es dazu nicht, ich habe das nur geschlossen, weil es so lange inaktiv war.
