### ISSUE TITLE
Einstieg durch Dockerimage erleichtern

### ISSUE THREAD

**Issue by rattermeyer** [opitzconsulting/orcas#39]
Das Installieren Kapitel listet einige Tools und Schritte auf, die manuell durchgeführt werden müsen.
Idee: Stattdessen dockerimage / dockerfile bereitstellen mit Tools und lokales Entwicklerverzeichnis als Volume mounten.

ggf. gehört dazu dann noch ein Script, welches angepasst werden muss.

Idee:
- Docker Pull
- Skript ausführen
- Datenbank besuchen und sich freuen

**Comment by rattermeyer** [comment]
Ggf. könnte man das auf einem geplanten docker hack day als Beispiel nehmen ... Docker Hack day ca für März / April überlegt.

**Comment by llsand** [comment]
orcas ist jetzt in maven central verfügbar, somit ist eine docker-runtime nicht mehr sinnvoll
es gibt aber eine docker-basieret integrationmstest-umgebung (orcas_docker)
