### ISSUE TITLE
use orcas offline

### ISSUE THREAD

**Issue by llsand** [opitzconsulting/orcas#52]
Orcas requires an internet connection for updating a schema.
It needs this connection for resolving maven-dependencies.
It should be possible to pre-build orcas, so that the update-run does no longer depends on an active internet connection.

**Comment by stefanscheidt** [comment]
This should only be neccessary the first time the schema update runs, right? You could prepare for going offline via `mvn dependency:go-offline`, see <https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html>

**Comment by llsand** [comment]
> This should only be neccessary the first time the schema update runs, right? 
Yes
> You could prepare for going offline via mvn dependency:go-offline, see https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html

It is important, that an orcas installation can run without ever having an internet connection. The idea was to run orcas on an machine with internet connection an create a file that enbables another orcas installation on a dirfferent machine to run orcas offline.

**Comment by stefanscheidt** [comment]
It's possible to add a file base repository to the list of repositories maven queries to resolve dependencies, e.g. like so in your `pom.xml`:

```
<repositories>
    <!--other repositories if any-->
    <repository>
        <id>project.local</id>
        <name>project</name>
        <url>file:${project.basedir}/repo</url>
    </repository>
</repositories>
```

So probabliy you can
1.   make a complete build on a system with an empty local maven repo (`mv ~/.m2/repository ~/.m2/repo.bak`) to populate the local repo with the dependencies needed to build the project
1.   copy the local maven repo to ${project.basedir}/repo
1.   add this folder as a file based repo to your pom as shown above
1.   restore you original local repo if needed
