### ISSUE TITLE
convert ant tasks to gradle plugins

### ISSUE THREAD

**Issue by tpd-opitz** [opitzconsulting/orcas#54]
many projects gave up ant for a more convenient build tool. 
also currently orcas depends on an outdated ant related dependency.

please convert the parts of orcas which depend on ant (and ant related stuff) to gradle plugins to avoid the need of ant beeing installed.

bye
Thomas

**Comment by llsand** [comment]
plugins for gradle and maven have been added.
see examples/gradle or examples/maven
