### ISSUE TITLE
Export von Sequences - maxvalue

### ISSUE THREAD

**Issue by jwinkels** [opitzconsulting/orcas#61]
Wenn der maxvalue einer Sequence vom Standard abweicht, ist der extrahierte maxvalue falsch.
Im vorliegenden Fall ist der extrahierte Wert negativ.

**Comment by llsand** [comment]
Bitte konkretes Beispiel anfügen.
Der Integrationstest (orcas_integrationstest\tests\test_sequence; mit maxvalue) funktioniert.

**Comment by tjaeschke** [comment]
Der Fehler wurde inzwischen behoben
